version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=espacios
    volumes:
      - /home/data:/var/lib/mysql
    ports:
      - '3306:3306'

  web:
    build: .
    command: bash -c 'asadmin start-domain -v' run
    ports:
      - '8080:8080'
      - '4848:4848'
    depends_on:
      - db